# ~/.bash_profile: loaded by bash(1) when it is initiated.

##
# Add ~/.bin to $PATH.
##
export PATH="$PATH:$HOME/.local/bin:$HOME/.bin"

##
# Source prompt configurations from other files.
##
source $HOME/".bash_prompt"
source $HOME/".bash_aliases"
