language: bash

sudo: required

before_install:
    - echo "deb http://archive.ubuntu.com/ubuntu/ wily universe" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -q
    - sudo apt-get install shellcheck -y

script:
  - tests/syntax_tests.sh

branches:
  only:
    - master
